//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC5HomeWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v客戶資料
    {
        public int Id { get; set; }
        public string 客戶名稱 { get; set; }
        public string 統一編號 { get; set; }
        public string 電話 { get; set; }
        public string 傳真 { get; set; }
        public string 地址 { get; set; }
        public string Email { get; set; }
        public bool 是否已刪除 { get; set; }
        public string 銀行名稱 { get; set; }
        public int 銀行代碼 { get; set; }
        public Nullable<int> 分行代碼 { get; set; }
        public string 帳戶名稱 { get; set; }
        public string 帳戶號碼 { get; set; }
        public bool 客戶銀行資訊_是否已刪除 { get; set; }
        public string 職稱 { get; set; }
        public string 客戶聯絡人_姓名 { get; set; }
        public string 客戶聯絡人_Email { get; set; }
        public string 客戶聯絡人_手機 { get; set; }
        public string 客戶聯絡人_電話 { get; set; }
        public bool 客戶聯絡人_是否已刪除 { get; set; }
    }
}
